"""
scripts/generate_snapshot_sql.py

Generates a complete SQL file to:
  1. Add a scope_key column to public.overview_kpis_snapshot (idempotent)
  2. Add a UNIQUE constraint on scope_key (idempotent)
  3. Upsert one snapshot row per unique access profile, read from the `auth`
     database tables (user_creds / user_disease_areas / user_drug_classes)

Run from the project root:
    python scripts/generate_snapshot_sql.py

Output: scripts/snapshot_upsert.sql   (run this file on your database)

The scope-key math and KPI SQL live in backend/src/services/snapshot_sql.py so
this script, scripts/apply_snapshot_upserts.py, and the admin "Rebuild snapshots"
endpoint all share one implementation. This script only emits SQL; it does not
execute anything against the KPI database.
"""
from __future__ import annotations

import sys
from pathlib import Path
from datetime import datetime, timezone

# Allow importing the backend package (shared snapshot logic lives in backend/src).
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend" / "src"))

from data.auth_repository import get_all_access
# Shared SQL builders — single source of truth (build_scope_key is re-exported
# here for scripts/verify_user_snapshot.py).
from services.snapshot_sql import (  # noqa: F401
    resolve_scope,
    build_scope_key,
    build_scope_subquery,
    build_upsert_block,
)


# ── Main ──────────────────────────────────────────────────────────────────────

def generate() -> str:
    lines: list[str] = []

    lines.append(f"""\
-- =============================================================================
-- overview_kpis_snapshot — scoped snapshot upserts
-- Generated by scripts/generate_snapshot_sql.py on {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}
--
-- HOW TO USE:
--   1. Run the SCHEMA section once (adds scope_key column + unique constraint).
--   2. Run the UPSERT section whenever user access profiles change.
--      Each statement is idempotent — safe to re-run.
-- =============================================================================

-- ── SCHEMA (run once) ────────────────────────────────────────────────────────

-- Create the target table on a fresh database (idempotent — no-op if it exists).
CREATE TABLE IF NOT EXISTS public.overview_kpis_snapshot (
    scope_key           TEXT PRIMARY KEY,
    total_trials        BIGINT,
    active_trials       BIGINT,
    completed_trials    BIGINT,
    trials_with_results BIGINT,
    median_enrollment   NUMERIC,
    unique_sponsors     BIGINT,
    unique_drugs        BIGINT,
    unique_conditions   BIGINT,
    trials_with_pros    BIGINT,
    refreshed_at        TIMESTAMPTZ
);

-- Migrate an older table that predates scope_key (no-op on a freshly created one).
ALTER TABLE public.overview_kpis_snapshot
    ADD COLUMN IF NOT EXISTS scope_key TEXT NOT NULL DEFAULT 'global';

-- Back-fill existing rows as 'global' (if any were inserted before this migration)
UPDATE public.overview_kpis_snapshot
SET scope_key = 'global'
WHERE scope_key IS NULL OR scope_key = '';

ALTER TABLE public.overview_kpis_snapshot
    DROP CONSTRAINT IF EXISTS overview_kpis_snapshot_scope_key_key;

ALTER TABLE public.overview_kpis_snapshot
    ADD CONSTRAINT overview_kpis_snapshot_scope_key_key UNIQUE (scope_key);

-- ── UPSERTS (re-run whenever access profiles change) ─────────────────────────
""")

    # Read every user's access profile from the auth DB tables.
    user_access = get_all_access()

    # Collect unique profiles — deduplicate by scope_key so users with identical
    # access don't generate duplicate SQL blocks.
    seen: dict[str, tuple] = {}   # scope_key → (disease_areas, drug_classes)
    for username, cfg in user_access.items():
        disease_areas, drug_classes = resolve_scope(cfg)
        key = build_scope_key(disease_areas, drug_classes)
        seen.setdefault(key, (disease_areas, drug_classes))

    # Always include global
    seen.setdefault("global", (None, None))

    # Sort so global comes first, then alphabetically
    ordered = sorted(seen.items(), key=lambda kv: (kv[0] != "global", kv[0]))

    users_per_scope: dict[str, list[str]] = {}
    for username, cfg in user_access.items():
        key = build_scope_key(*resolve_scope(cfg))
        users_per_scope.setdefault(key, []).append(username)

    for scope_key, (disease_areas, drug_classes) in ordered:
        users = users_per_scope.get(scope_key, [])
        if users:
            lines.append(f"-- Users with this scope: {', '.join(sorted(users))}\n")
        subquery = build_scope_subquery(disease_areas, drug_classes)
        lines.append(build_upsert_block(scope_key, subquery))

    lines.append("-- End of generated SQL\n")
    return "\n".join(lines)


if __name__ == "__main__":
    output_path = Path(__file__).parent / "snapshot_upsert.sql"
    sql = generate()
    output_path.write_text(sql, encoding="utf-8")
    print(f"Written to: {output_path}")
    print()
    print("Scopes generated:")
    seen: dict[str, list[str]] = {}
    for username, cfg in get_all_access().items():
        key = build_scope_key(*resolve_scope(cfg))
        seen.setdefault(key, []).append(username)
    for key, users in sorted(seen.items()):
        label = key if len(key) <= 60 else key[:57] + "..."
        print(f"  {label:<60}  (users: {', '.join(sorted(users))})")
