-- =============================================================================
-- overview_kpis_snapshot — scoped snapshot upserts
-- Generated by scripts/generate_snapshot_sql.py on 2026-07-06 17:10 UTC
--
-- HOW TO USE:
--   1. Run the SCHEMA section once (adds scope_key column + unique constraint).
--   2. Run the UPSERT section whenever user access profiles change.
--      Each statement is idempotent — safe to re-run.
-- =============================================================================

-- ── SCHEMA (run once) ────────────────────────────────────────────────────────

-- Create the target table on a fresh database (idempotent — no-op if it exists).
CREATE TABLE IF NOT EXISTS public.overview_kpis_snapshot (
    scope_key           TEXT PRIMARY KEY,
    total_trials        BIGINT,
    active_trials       BIGINT,
    completed_trials    BIGINT,
    trials_with_results BIGINT,
    median_enrollment   NUMERIC,
    unique_sponsors     BIGINT,
    unique_drugs        BIGINT,
    unique_conditions   BIGINT,
    trials_with_pros    BIGINT,
    refreshed_at        TIMESTAMPTZ
);

-- Migrate an older table that predates scope_key (no-op on a freshly created one).
ALTER TABLE public.overview_kpis_snapshot
    ADD COLUMN IF NOT EXISTS scope_key TEXT NOT NULL DEFAULT 'global';

-- Back-fill existing rows as 'global' (if any were inserted before this migration)
UPDATE public.overview_kpis_snapshot
SET scope_key = 'global'
WHERE scope_key IS NULL OR scope_key = '';

ALTER TABLE public.overview_kpis_snapshot
    DROP CONSTRAINT IF EXISTS overview_kpis_snapshot_scope_key_key;

ALTER TABLE public.overview_kpis_snapshot
    ADD CONSTRAINT overview_kpis_snapshot_scope_key_key UNIQUE (scope_key);

-- ── UPSERTS (re-run whenever access profiles change) ─────────────────────────

-- Users with this scope: User2, admin, sahil

-- ── Scope: global ────────────────────────────────────────────────────────
INSERT INTO public.overview_kpis_snapshot (
    scope_key,
    total_trials,
    active_trials,
    completed_trials,
    trials_with_results,
    median_enrollment,
    unique_sponsors,
    unique_drugs,
    unique_conditions,
    trials_with_pros,
    refreshed_at
)
WITH scoped AS (
    SELECT s.nct_id,
           s.overall_status,
           s.enrollment,
           s.results_first_submitted_date
    FROM ctgov.studies s
    WHERE s.nct_id IN (SELECT DISTINCT nct_id FROM public.drug_trials)
),
kpi_main AS (
    SELECT
        COUNT(DISTINCT nct_id)                                                         AS total_trials,
        COUNT(DISTINCT CASE WHEN overall_status IN
            ('RECRUITING', 'ACTIVE_NOT_RECRUITING') THEN nct_id END)                   AS active_trials,
        COUNT(DISTINCT CASE WHEN overall_status = 'COMPLETED' THEN nct_id END)         AS completed_trials,
        COUNT(DISTINCT CASE WHEN results_first_submitted_date IS NOT NULL
            THEN nct_id END)                                                           AS trials_with_results,
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY enrollment)                        AS median_enrollment
    FROM scoped
),
kpi_sponsors AS (
    SELECT COUNT(DISTINCT sp.name) AS unique_sponsors
    FROM ctgov.sponsors sp
    WHERE sp.nct_id IN (SELECT nct_id FROM scoped)
      AND sp.lead_or_collaborator = 'lead'
),
kpi_drugs AS (
    SELECT COUNT(DISTINCT dt.brand_name) AS unique_drugs
    FROM public.drug_trials dt
    WHERE dt.nct_id IN (SELECT nct_id FROM scoped)
),
kpi_conditions AS (
    SELECT COUNT(DISTINCT bc.downcase_mesh_term) AS unique_conditions
    FROM ctgov.browse_conditions bc
    WHERE bc.nct_id IN (SELECT nct_id FROM scoped)
      AND bc.mesh_type = 'mesh-list'
),
kpi_pros AS (
    SELECT COUNT(DISTINCT p.nct_id) AS trials_with_pros
    FROM public.drug_trial_design_outcomes_pro p
    WHERE p.nct_id IN (SELECT nct_id FROM scoped)
)
SELECT
    'global',
    kpi_main.total_trials,
    kpi_main.active_trials,
    kpi_main.completed_trials,
    kpi_main.trials_with_results,
    kpi_main.median_enrollment,
    kpi_sponsors.unique_sponsors,
    kpi_drugs.unique_drugs,
    kpi_conditions.unique_conditions,
    kpi_pros.trials_with_pros,
    '2026-07-06 17:10:53+00'::timestamptz
FROM kpi_main, kpi_sponsors, kpi_drugs, kpi_conditions, kpi_pros
ON CONFLICT (scope_key) DO UPDATE SET
    total_trials        = EXCLUDED.total_trials,
    active_trials       = EXCLUDED.active_trials,
    completed_trials    = EXCLUDED.completed_trials,
    trials_with_results = EXCLUDED.trials_with_results,
    median_enrollment   = EXCLUDED.median_enrollment,
    unique_sponsors     = EXCLUDED.unique_sponsors,
    unique_drugs        = EXCLUDED.unique_drugs,
    unique_conditions   = EXCLUDED.unique_conditions,
    trials_with_pros    = EXCLUDED.trials_with_pros,
    refreshed_at        = EXCLUDED.refreshed_at;

-- Users with this scope: User3, ambi

-- ── Scope: ind:Atopic Dermatitis / Eczema|Chronic Obstructive Pulmonary Disease|Migraine ────────────────────────────────────────────────────────
INSERT INTO public.overview_kpis_snapshot (
    scope_key,
    total_trials,
    active_trials,
    completed_trials,
    trials_with_results,
    median_enrollment,
    unique_sponsors,
    unique_drugs,
    unique_conditions,
    trials_with_pros,
    refreshed_at
)
WITH scoped AS (
    SELECT s.nct_id,
           s.overall_status,
           s.enrollment,
           s.results_first_submitted_date
    FROM ctgov.studies s
    WHERE s.nct_id IN (
        SELECT DISTINCT dt.nct_id
        FROM public.drug_trials dt
        JOIN ctgov.browse_conditions bc ON bc.nct_id = dt.nct_id
        WHERE bc.mesh_type = 'mesh-list'
          AND bc.downcase_mesh_term IN ('Atopic Dermatitis / Eczema', 'Migraine', 'Chronic Obstructive Pulmonary Disease')
    )
),
kpi_main AS (
    SELECT
        COUNT(DISTINCT nct_id)                                                         AS total_trials,
        COUNT(DISTINCT CASE WHEN overall_status IN
            ('RECRUITING', 'ACTIVE_NOT_RECRUITING') THEN nct_id END)                   AS active_trials,
        COUNT(DISTINCT CASE WHEN overall_status = 'COMPLETED' THEN nct_id END)         AS completed_trials,
        COUNT(DISTINCT CASE WHEN results_first_submitted_date IS NOT NULL
            THEN nct_id END)                                                           AS trials_with_results,
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY enrollment)                        AS median_enrollment
    FROM scoped
),
kpi_sponsors AS (
    SELECT COUNT(DISTINCT sp.name) AS unique_sponsors
    FROM ctgov.sponsors sp
    WHERE sp.nct_id IN (SELECT nct_id FROM scoped)
      AND sp.lead_or_collaborator = 'lead'
),
kpi_drugs AS (
    SELECT COUNT(DISTINCT dt.brand_name) AS unique_drugs
    FROM public.drug_trials dt
    WHERE dt.nct_id IN (SELECT nct_id FROM scoped)
),
kpi_conditions AS (
    SELECT COUNT(DISTINCT bc.downcase_mesh_term) AS unique_conditions
    FROM ctgov.browse_conditions bc
    WHERE bc.nct_id IN (SELECT nct_id FROM scoped)
      AND bc.mesh_type = 'mesh-list'
),
kpi_pros AS (
    SELECT COUNT(DISTINCT p.nct_id) AS trials_with_pros
    FROM public.drug_trial_design_outcomes_pro p
    WHERE p.nct_id IN (SELECT nct_id FROM scoped)
)
SELECT
    'ind:Atopic Dermatitis / Eczema|Chronic Obstructive Pulmonary Disease|Migraine',
    kpi_main.total_trials,
    kpi_main.active_trials,
    kpi_main.completed_trials,
    kpi_main.trials_with_results,
    kpi_main.median_enrollment,
    kpi_sponsors.unique_sponsors,
    kpi_drugs.unique_drugs,
    kpi_conditions.unique_conditions,
    kpi_pros.trials_with_pros,
    '2026-07-06 17:10:53+00'::timestamptz
FROM kpi_main, kpi_sponsors, kpi_drugs, kpi_conditions, kpi_pros
ON CONFLICT (scope_key) DO UPDATE SET
    total_trials        = EXCLUDED.total_trials,
    active_trials       = EXCLUDED.active_trials,
    completed_trials    = EXCLUDED.completed_trials,
    trials_with_results = EXCLUDED.trials_with_results,
    median_enrollment   = EXCLUDED.median_enrollment,
    unique_sponsors     = EXCLUDED.unique_sponsors,
    unique_drugs        = EXCLUDED.unique_drugs,
    unique_conditions   = EXCLUDED.unique_conditions,
    trials_with_pros    = EXCLUDED.trials_with_pros,
    refreshed_at        = EXCLUDED.refreshed_at;

-- Users with this scope: User1

-- ── Scope: ind:Breast Cancer|Lung Cancer ────────────────────────────────────────────────────────
INSERT INTO public.overview_kpis_snapshot (
    scope_key,
    total_trials,
    active_trials,
    completed_trials,
    trials_with_results,
    median_enrollment,
    unique_sponsors,
    unique_drugs,
    unique_conditions,
    trials_with_pros,
    refreshed_at
)
WITH scoped AS (
    SELECT s.nct_id,
           s.overall_status,
           s.enrollment,
           s.results_first_submitted_date
    FROM ctgov.studies s
    WHERE s.nct_id IN (
        SELECT DISTINCT dt.nct_id
        FROM public.drug_trials dt
        JOIN ctgov.browse_conditions bc ON bc.nct_id = dt.nct_id
        WHERE bc.mesh_type = 'mesh-list'
          AND bc.downcase_mesh_term IN ('Breast Cancer', 'Lung Cancer')
    )
),
kpi_main AS (
    SELECT
        COUNT(DISTINCT nct_id)                                                         AS total_trials,
        COUNT(DISTINCT CASE WHEN overall_status IN
            ('RECRUITING', 'ACTIVE_NOT_RECRUITING') THEN nct_id END)                   AS active_trials,
        COUNT(DISTINCT CASE WHEN overall_status = 'COMPLETED' THEN nct_id END)         AS completed_trials,
        COUNT(DISTINCT CASE WHEN results_first_submitted_date IS NOT NULL
            THEN nct_id END)                                                           AS trials_with_results,
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY enrollment)                        AS median_enrollment
    FROM scoped
),
kpi_sponsors AS (
    SELECT COUNT(DISTINCT sp.name) AS unique_sponsors
    FROM ctgov.sponsors sp
    WHERE sp.nct_id IN (SELECT nct_id FROM scoped)
      AND sp.lead_or_collaborator = 'lead'
),
kpi_drugs AS (
    SELECT COUNT(DISTINCT dt.brand_name) AS unique_drugs
    FROM public.drug_trials dt
    WHERE dt.nct_id IN (SELECT nct_id FROM scoped)
),
kpi_conditions AS (
    SELECT COUNT(DISTINCT bc.downcase_mesh_term) AS unique_conditions
    FROM ctgov.browse_conditions bc
    WHERE bc.nct_id IN (SELECT nct_id FROM scoped)
      AND bc.mesh_type = 'mesh-list'
),
kpi_pros AS (
    SELECT COUNT(DISTINCT p.nct_id) AS trials_with_pros
    FROM public.drug_trial_design_outcomes_pro p
    WHERE p.nct_id IN (SELECT nct_id FROM scoped)
)
SELECT
    'ind:Breast Cancer|Lung Cancer',
    kpi_main.total_trials,
    kpi_main.active_trials,
    kpi_main.completed_trials,
    kpi_main.trials_with_results,
    kpi_main.median_enrollment,
    kpi_sponsors.unique_sponsors,
    kpi_drugs.unique_drugs,
    kpi_conditions.unique_conditions,
    kpi_pros.trials_with_pros,
    '2026-07-06 17:10:53+00'::timestamptz
FROM kpi_main, kpi_sponsors, kpi_drugs, kpi_conditions, kpi_pros
ON CONFLICT (scope_key) DO UPDATE SET
    total_trials        = EXCLUDED.total_trials,
    active_trials       = EXCLUDED.active_trials,
    completed_trials    = EXCLUDED.completed_trials,
    trials_with_results = EXCLUDED.trials_with_results,
    median_enrollment   = EXCLUDED.median_enrollment,
    unique_sponsors     = EXCLUDED.unique_sponsors,
    unique_drugs        = EXCLUDED.unique_drugs,
    unique_conditions   = EXCLUDED.unique_conditions,
    trials_with_pros    = EXCLUDED.trials_with_pros,
    refreshed_at        = EXCLUDED.refreshed_at;

-- End of generated SQL
